import type { WizardConfig, ServerConfig, Module } from "../types.js";

/**
 * Generate the .env contents for the main (local) server.
 */
export function generateMainEnv(config: WizardConfig): string {
  const d = config.domain;
  const isLocal = config.isLocalOnly;
  const scheme = isLocal ? "http" : "https";
  const url = `${scheme}://${d}`;

  // Determine where each module lives
  const imagesServer = findModuleServer(config, "images");
  const moderationServer = findModuleServer(config, "moderation");
  const livekitServer = findModuleServer(config, "livekit");
  const minioServer = findModuleServer(config, "minio");
  const mainServer = config.servers[0];

  // imgproxy URL: internal if co-located, external if on another server
  let imgproxyUrl = "";
  if (imagesServer) {
    imgproxyUrl =
      imagesServer.id === mainServer.id
        ? "http://imgproxy:8080"
        : `https://img.${d}`;
  }

  // content moderation URL
  let contentModerationUrl = "";
  if (moderationServer) {
    contentModerationUrl =
      moderationServer.id === mainServer.id
        ? "http://nsfwjs:5000"
        : `https://moderation.${d}`;
  }

  // Storage: MinIO or external S3
  let s3Endpoint = config.s3Endpoint || "";
  let storageAccountId = config.storageAccountId || "";
  let storageAccessKeyId = config.storageAccessKeyId || "";
  let storageSecretAccessKey = config.storageSecretAccessKey || "";
  let storageBucketName = config.storageBucketName || "";
  let storagePublicUrl = config.storagePublicUrl || "";
  let attachmentsBucketName = config.attachmentsBucketName || "";
  let attachmentsBaseUrl = config.attachmentsBaseUrl || "";

  if (minioServer) {
    const minioDomain = isLocal ? "localhost:9000" : `s3.${d}`;
    s3Endpoint =
      minioServer.id === mainServer.id
        ? "http://minio:9000"
        : `https://s3.${d}`;
    storageAccessKeyId = config.minioRootUser || "gatherend";
    storageSecretAccessKey = config.minioRootPassword || "";
    storageBucketName = storageBucketName || "gatherend";
    storagePublicUrl = storagePublicUrl || `${scheme}://${minioDomain}/${storageBucketName}`;
    attachmentsBucketName = attachmentsBucketName || "attachments";
    attachmentsBaseUrl = attachmentsBaseUrl || `${scheme}://${minioDomain}/${attachmentsBucketName}`;
  }

  const mediaAllowedHostnames = [
    getHostname(storagePublicUrl),
    getHostname(attachmentsBaseUrl),
  ]
    .filter(Boolean)
    .join(",");

  const lines: string[] = [
    `# Generated by Gatherend Setup Wizard`,
    `# ${new Date().toISOString()}`,
    ``,
    `# --- Core ---`,
    `POSTGRES_USER=gatherend`,
    `POSTGRES_PASSWORD=${config.postgresPassword}`,
    `POSTGRES_DB=gatherend`,
    `REDIS_PASSWORD=${config.redisPassword}`,
    ``,
    `# --- Auth ---`,
    `BETTER_AUTH_SECRET=${config.betterAuthSecret}`,
    `BETTER_AUTH_URL=${url}`,
    `EMAIL_VERIFICATION_ENABLED=false`,
    `INTERNAL_API_SECRET=${config.internalApiSecret}`,
    ``,
    `# --- Cloudflare ---`,
    `CF_ORIGIN_SECRET=${config.cfOriginSecret}`,
    ``,
    `# --- Storage ---`,
    `S3_ENDPOINT=${s3Endpoint}`,
    `STORAGE_ACCOUNT_ID=${storageAccountId}`,
    `STORAGE_ACCESS_KEY_ID=${storageAccessKeyId}`,
    `STORAGE_SECRET_ACCESS_KEY=${storageSecretAccessKey}`,
    `STORAGE_BUCKET_NAME=${storageBucketName}`,
    `STORAGE_PUBLIC_URL=${storagePublicUrl}`,
    `ATTACHMENTS_BUCKET_NAME=${attachmentsBucketName}`,
    `ATTACHMENTS_BASE_URL=${attachmentsBaseUrl}`,
    `ATTACHMENTS_HMAC_KEY=${config.attachmentsHmacKey}`,
    ``,
    `# --- imgproxy ---`,
    `IMGPROXY_URL=${imgproxyUrl}`,
    `IMGPROXY_KEY=${config.imgproxyKey || ""}`,
    `IMGPROXY_SALT=${config.imgproxySalt || ""}`,
    ``,
    `# --- Content Moderation ---`,
    `CONTENT_MODERATION_URL=${contentModerationUrl}`,
    `CONTENT_MODERATION_API_KEY=${config.contentModerationApiKey || ""}`,
    ``,
    `# --- LiveKit ---`,
    `LIVEKIT_API_KEY=${config.livekitApiKey || ""}`,
    `LIVEKIT_API_SECRET=${config.livekitApiSecret || ""}`,
    ``,
    `# --- SMTP ---`,
    `SMTP_HOST=${config.smtpHost || ""}`,
    `SMTP_PORT=${config.smtpPort || 587}`,
    `SMTP_USER=${config.smtpUser || ""}`,
    `SMTP_PASS=${config.smtpPass || ""}`,
    `SMTP_FROM=${config.smtpFrom || ""}`,
    `SMTP_FROM_NAME=${config.smtpFromName || ""}`,
    ``,
    `# --- OAuth ---`,
    `DISCORD_CLIENT_ID=${config.discordClientId || ""}`,
    `DISCORD_CLIENT_SECRET=${config.discordClientSecret || ""}`,
    `GOOGLE_CLIENT_ID=${config.googleClientId || ""}`,
    `GOOGLE_CLIENT_SECRET=${config.googleClientSecret || ""}`,
    ``,
    `# --- Admin ---`,
    `CRON_SECRET=${config.cronSecret}`,
  ];

  // MinIO on main server
  if (minioServer?.id === mainServer.id) {
    lines.push(
      ``,
      `# --- MinIO ---`,
      `MINIO_ROOT_USER=${config.minioRootUser || "gatherend"}`,
      `MINIO_ROOT_PASSWORD=${config.minioRootPassword || ""}`
    );
  }

  // LiveKit on main server
  if (livekitServer?.id === mainServer.id) {
    lines.push(
      ``,
      `# --- LiveKit (local) ---`,
      `LIVEKIT_DOMAIN=media.${d}`,
      `LIVEKIT_TURN_DOMAIN=turn.${d}`
    );
  }

  // URLs
  lines.push(
    ``,
    `# --- URLs ---`,
    `FRONTEND_URL=${url}`,
    `SITE_URL=${url}`,
    `MEDIA_ALLOWED_HOSTNAMES=${mediaAllowedHostnames}`,
    ``,
    `# --- Build-time ---`,
    `NEXT_PUBLIC_API_URL=${url}/api/r2`,
    `NEXT_PUBLIC_SOCKET_URL=${url}/api/r2`,
    `NEXT_PUBLIC_LIVEKIT_URL=${livekitServer ? `wss://media.${d}` : ""}`,
    `NEXT_PUBLIC_CDN_URL=${storagePublicUrl}`,
    `NEXT_PUBLIC_IMGPROXY_URL=${imagesServer && !isLocal ? `https://img.${d}` : ""}`,
    `NEXT_PUBLIC_STORAGE_DOMAIN=${getHostname(storagePublicUrl)}`,
    `NEXT_PUBLIC_BETTER_AUTH_URL=${url}`,
    `NEXT_PUBLIC_DICEBEAR_URL=${imagesServer && !isLocal ? `https://avatars.${d}` : ""}`
  );

  // Caddy env vars (used in generated Caddyfile)
  if (!isLocal) {
    lines.push(
      ``,
      `# --- Caddy domains ---`,
      `APP_DOMAIN=${d}`
    );
    if (imagesServer?.id === mainServer.id) {
      lines.push(
        `IMAGES_DOMAIN=img.${d}`,
        `AVATARS_DOMAIN=avatars.${d}`
      );
    }
    if (moderationServer?.id === mainServer.id) {
      lines.push(`MODERATION_DOMAIN=moderation.${d}`);
    }
    if (minioServer?.id === mainServer.id) {
      lines.push(`MINIO_DOMAIN=s3.${d}`);
    }
    if (livekitServer?.id === mainServer.id) {
      lines.push(
        `LIVEKIT_DOMAIN=media.${d}`,
        `LIVEKIT_TURN_DOMAIN=turn.${d}`
      );
    }
  }

  lines.push(``);
  return lines.join("\n");
}

/**
 * Generate the .env contents for a services (remote) server.
 */
export function generateServicesEnv(
  config: WizardConfig,
  server: ServerConfig
): string {
  const d = config.domain;

  const lines: string[] = [
    `# Generated by Gatherend Setup Wizard`,
    `# Server ${server.id} — ${server.ip}`,
    `# ${new Date().toISOString()}`,
    ``,
    `# --- Domains ---`,
    `APP_DOMAIN=${d}`,
  ];

  if (server.modules.includes("images")) {
    lines.push(
      `IMAGES_DOMAIN=img.${d}`,
      `AVATARS_DOMAIN=avatars.${d}`
    );
  }

  if (server.modules.includes("moderation")) {
    lines.push(
      `MODERATION_DOMAIN=moderation.${d}`,
      ``,
      `# --- Content Moderation ---`,
      `CONTENT_MODERATION_API_KEY=${config.contentModerationApiKey || ""}`
    );
  }

  if (server.modules.includes("images")) {
    lines.push(
      ``,
      `# --- imgproxy ---`,
      `IMGPROXY_KEY=${config.imgproxyKey || ""}`,
      `IMGPROXY_SALT=${config.imgproxySalt || ""}`
    );
  }

  if (server.modules.includes("minio")) {
    lines.push(
      ``,
      `# --- MinIO ---`,
      `MINIO_ROOT_USER=${config.minioRootUser || "gatherend"}`,
      `MINIO_ROOT_PASSWORD=${config.minioRootPassword || ""}`
    );
  }

  if (server.modules.includes("livekit")) {
    lines.push(
      ``,
      `# --- LiveKit ---`,
      `LIVEKIT_DOMAIN=media.${d}`,
      `LIVEKIT_TURN_DOMAIN=turn.${d}`
    );
  }

  lines.push(``);
  return lines.join("\n");
}

function findModuleServer(
  config: WizardConfig,
  module: Module
): ServerConfig | undefined {
  return config.servers.find((s) => s.modules.includes(module));
}

function getHostname(url: string | undefined): string {
  if (!url) return "";
  try {
    return new URL(url).hostname;
  } catch {
    return "";
  }
}
